// Generated by Tools/SpotiPW/extract-flags.py from a decrypted Spotify IPA. Do not edit.
//
// PLACEHOLDER: the real table is extracted from the Spotify IPA you build against, so every
// build regenerates it (build-ipa-local.sh and the GitHub workflows do this automatically).
// Until it is regenerated this placeholder yields an empty "All flags" page; everything else
// in the spoti.pw section keeps working.
#import "Flags.h"

const SGFlagDef SGFlagTable[] = {};
const NSUInteger SGFlagCount = sizeof(SGFlagTable) / sizeof(*SGFlagTable);
